### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by J-Bannach** [J-Bannach/21ideas#15]
#### Prepare routes for API requests

Add src/server/routes.ts and implement routes for the API requests.

#### Example

https://github.com/lmachens/photoplay/pull/49/files#diff-fde59f82d5255c9a937bb3bc6e705db248415d663110d89907b7674a79a62fce

#### Tasks

Prepare routes for:

- [x]  save selected meals in overview per week 
- [x]  save selected meals in overview per day 
- [x]  see recipe per meal /breakfast /lunch /dinner
