### ISSUE TITLE
Prepare routes

### ISSUE THREAD

**Issue by J-Bannach** [J-Bannach/21ideas#2]
#### Prepare routes for API requests

Add src/server/routes.ts and implement routes for the API requests.

#### Example

 https://github.com/lmachens/photoplay/pull/49/files#diff-fde59f82d5255c9a937bb3bc6e705db248415d663110d89907b7674a79a62fce

#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.

- [x] Define API
- [x] Add src/server/routes.ts
- [x] Create samples.http
- [x] Implement error handling
