### ISSUE TITLE
Create paths between pages

### ISSUE THREAD

**Issue by J-Bannach** [J-Bannach/21ideas#20]
#### Description

Create paths between pages in App.tsx:

1. from landing page to home (weekly overview)
2. from home to day page
<img width="706" alt="Screenshot 2021-06-20 at 13 26 55" src="https://user-images.githubusercontent.com/78214585/122672297-31dc0080-d1cb-11eb-8fdc-2b9dde422fa3.png">

3. from meal on day page (e.g. breakfast) to recipe page
<img width="611" alt="Screenshot 2021-06-20 at 13 27 31" src="https://user-images.githubusercontent.com/78214585/122672314-4a4c1b00-d1cb-11eb-9728-cb2744d6c7b2.png">

#### Tasks

- [x] Task 1: Link to home (weekly overview)
- [x] Task 2: One route per day required (/monday, /tuesday etc.)
- [x] Task 3: One route per meal and day required (/monday/breakfast, /tuesday/lunch etc.)
