### ISSUE TITLE
Define API

### ISSUE THREAD

**Issue by J-Bannach** [J-Bannach/21ideas#4]
#### Define API 

Get all necessary information for API integration:

#### Tasks

- [x] How is the API structured: which information is accessible?
- [x] How to send and process requests
- [x] API Key?
- [x] How many requests possible for free (debounce!)?
