### ISSUE TITLE
Add sample.HTTP file

### ISSUE THREAD

**Issue by J-Bannach** [J-Bannach/21ideas#5]
#### Add sample HTTP file

Add sample HTTP file with custom port and proxy.

#### Example

https://github.com/lmachens/photoplay/pull/49/commits/72b70aa2c7fff748c1e2bf021a00293a950c8945

#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.

- [x] Add proxy to API
- [x] Build sample.HTTP
- [x] Test sample.HTTP and check data
