### ISSUE TITLE
Build API.ts

### ISSUE THREAD

**Issue by J-Bannach** [J-Bannach/21ideas#6]
#### Create fetch function

Create environment  for fetch function to retrieve requested API data

#### Example

```async function fetchTheMovieDB<T>(path: string, query = ''): Promise<T> {
  let url = `${BASE_URL}${path}?`;
  if (query) {
    url += `${query}&`;
  }
  url += `api_key=${THE_MOVIE_DB_KEY}`;

  const response = await fetch(url);
  if (!response.ok) {
    const errorResult: ErrorResult = await response.json();
    throw {
      message: errorResult.status_message,
      theMovieDBCode: errorResult.status_code,
      status: response.status,
    };
  }
  const result: T = await response.json();
  return result;
}
```
Pull request:
https://github.com/lmachens/photoplay/pull/49/commits/cb547e8bace337d68a1385fdc2c438ae314e2974#diff-15c7576c5aab265c9a6f2a02b1e0061e6bc9bb8474be29c3f529f2ba8d6ad519

#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.

- [ ] Create BASE_URL
- [ ] Create fetch functions
- [ ] Create functions for API Search
